#!/usr/bin/env python3
"""Generate the two tiny Code_Aster 17.4 point-impact decks.

This only writes checked-in text inputs. It never launches Code_Aster.
"""

from __future__ import annotations

import argparse
from pathlib import Path


ROOT = Path(__file__).resolve().parent
END_TIME = 0.24
CONTACT_TIME = 0.10
CONTACT_DURATION = 0.08
MASS_1 = 1.0
MASS_2 = 2.0
RADIUS_1 = 0.5
RADIUS_2 = 0.5
INITIAL_SEPARATION = 2.0
INITIAL_VELOCITY_1 = 10.0
INITIAL_VELOCITY_2 = 0.0
REDUCED_MASS = MASS_1 * MASS_2 / (MASS_1 + MASS_2)
OMEGA = 3.141592653589793 / CONTACT_DURATION
NORMAL_STIFFNESS = REDUCED_MASS * OMEGA**2

CASES = {
    "coarse": (0.0025, "impact_coarse.med"),
    "fine": (0.00125, "impact_fine.med"),
}


def mesh_text() -> str:
    return """TITRE
* Two translating point masses and one axial impact SEG2; mm-tonne-s units.
FINSF
COOR_3D
N1 0.0 0.0 0.0
N2 2.0 0.0 0.0
FINSF
POI1
M1 N1
M2 N2
FINSF
SEG2
HIT1 N1 N2
FINSF
GROUP_MA
MASS1 M1
FINSF
GROUP_MA
MASS2 M2
FINSF
GROUP_MA
HITPAIR HIT1
FINSF
GROUP_NO
NODE1 N1
FINSF
GROUP_NO
NODE2 N2
FINSF
GROUP_NO
ALLN N1 N2
FINSF
FIN
"""


def comm_text(case_name: str, step: float, med_name: str) -> str:
    return f"""# Generated by generate.py. Case={case_name}, dt={step:g} s.
# Local 1D discrete penalty impact only; see README.md for limits.
DEBUT();

MAIL = LIRE_MAILLAGE(UNITE=20, FORMAT='ASTER');

MODEL = AFFE_MODELE(
    MAILLAGE=MAIL,
    AFFE=(
        _F(GROUP_MA=('MASS1', 'MASS2', 'HITPAIR'),
           PHENOMENE='MECANIQUE', MODELISATION='DIS_T'),
    ),
);

# Dummy zero-density elastic material on the point-mass POI1 elements.
# Inertia is assigned explicitly below with M_T_D_N.
MAT_MASS = DEFI_MATERIAU(ELAS=_F(E=1.0, NU=0.3, RHO=0.0));
MAT_HIT = DEFI_MATERIAU(DIS_CONTACT=_F(
    RIGI_NOR={NORMAL_STIFFNESS:.15g},
    RIGI_TAN=0.0,
    AMOR_NOR=0.0,
    AMOR_TAN=0.0,
    COULOMB=0.0,
    DIST_1={RADIUS_1:g},
    DIST_2={RADIUS_2:g},
));
CHMAT = AFFE_MATERIAU(
    MAILLAGE=MAIL,
    AFFE=(
        _F(GROUP_MA=('MASS1', 'MASS2'), MATER=MAT_MASS),
        _F(GROUP_MA='HITPAIR', MATER=MAT_HIT),
    ),
);

# A zero elastic discrete card accompanies the nonlinear DIS_CHOC relation,
# as in the stock SDND102B setup. The material RIGI_NOR controls the penalty.
CARA = AFFE_CARA_ELEM(
    MODELE=MODEL,
    DISCRET=(
        _F(REPERE='GLOBAL', CARA='K_T_D_L', GROUP_MA='HITPAIR',
           VALE=(0.0, 0.0, 0.0)),
        _F(REPERE='GLOBAL', CARA='M_T_L', GROUP_MA='HITPAIR',
           VALE=(0.0,) * 21),
        _F(REPERE='GLOBAL', CARA='A_T_D_L', GROUP_MA='HITPAIR',
           VALE=(0.0, 0.0, 0.0)),
        _F(CARA='M_T_D_N', GROUP_MA='MASS1', VALE={MASS_1:g}),
        _F(CARA='K_T_D_N', GROUP_MA='MASS1', VALE=(0.0, 0.0, 0.0)),
        _F(CARA='A_T_D_N', GROUP_MA='MASS1', VALE=(0.0, 0.0, 0.0)),
        _F(CARA='M_T_D_N', GROUP_MA='MASS2', VALE={MASS_2:g}),
        _F(CARA='K_T_D_N', GROUP_MA='MASS2', VALE=(0.0, 0.0, 0.0)),
        _F(CARA='A_T_D_N', GROUP_MA='MASS2', VALE=(0.0, 0.0, 0.0)),
    ),
);

# Only the axial translational DOF is free. The incoming speed is an initial
# velocity; there is no applied force or imposed motion after t=0.
BC = AFFE_CHAR_MECA(
    MODELE=MODEL,
    DDL_IMPO=_F(GROUP_NO='ALLN', DY=0.0, DZ=0.0),
);
V0 = CREA_CHAMP(
    TYPE_CHAM='NOEU_DEPL_R',
    OPERATION='AFFE',
    MODELE=MODEL,
    AFFE=(
        _F(GROUP_NO='NODE1', NOM_CMP=('DX', 'DY', 'DZ'),
           VALE=({INITIAL_VELOCITY_1:g}, 0.0, 0.0)),
        _F(GROUP_NO='NODE2', NOM_CMP=('DX', 'DY', 'DZ'),
           VALE=({INITIAL_VELOCITY_2:g}, 0.0, 0.0)),
    ),
);

TINST = DEFI_LIST_REEL(
    DEBUT=0.0,
    INTERVALLE=_F(JUSQU_A={END_TIME:g}, PAS={step:.10g}),
);

RESU = DYNA_NON_LINE(
    MODELE=MODEL,
    CHAM_MATER=CHMAT,
    CARA_ELEM=CARA,
    EXCIT=_F(CHARGE=BC),
    COMPORTEMENT=(
        _F(RELATION='ELAS', GROUP_MA=('MASS1', 'MASS2'),
           DEFORMATION='PETIT'),
        _F(RELATION='DIS_CHOC', GROUP_MA='HITPAIR'),
    ),
    ETAT_INIT=_F(VITE=V0),
    INCREMENT=_F(LIST_INST=TINST),
    SCHEMA_TEMPS=_F(SCHEMA='NEWMARK', FORMULATION='DEPLACEMENT',
                    BETA=0.25, GAMMA=0.5),
    NEWTON=_F(REAC_ITER=1),
    # Absolute force tolerance avoids a zero-force relative denominator during
    # the free approach; units are N in the stated mm-tonne-s system.
    CONVERGENCE=_F(RESI_GLOB_MAXI=1.0e-9, ITER_GLOB_MAXI=20),
    ARCHIVAGE=_F(LIST_INST=TINST),
    ENERGIE=_F(),
    TITRE='Frictionless two-mass free-impact known answer ({case_name})',
);

# Preserve nodal displacement/velocity/acceleration and the discrete force
# field for independent comparison with oracle.json.
IMPR_RESU(
    FORMAT='MED',
    UNITE=80,
    RESU=_F(RESULTAT=RESU, NOM_CHAM=('DEPL', 'VITE', 'ACCE', 'SIEF_ELGA')),
);
TAB_EN = RECU_TABLE(CO=RESU, NOM_TABLE='PARA_CALC');
IMPR_TABLE(FORMAT='TABLEAU', UNITE=6, TABLE=TAB_EN);

FIN();
"""


def export_text(case_name: str, med_name: str) -> str:
    return f"""P actions make_etude
P mode interactif
P ncpus 1
P mpi_nbcpu 1
P mpi_nbnoeud 1
P time_limit 300
P memory_limit 1024
F comm impact.comm D 1
F mail impact.mail D 20
F mess impact.mess R 6
F rmed {med_name} R 80
"""


def expected_files() -> dict[Path, str]:
    generated: dict[Path, str] = {}
    for case_name, (step, med_name) in CASES.items():
        case_dir = ROOT / case_name
        generated[case_dir / 'impact.mail'] = mesh_text()
        generated[case_dir / 'impact.comm'] = comm_text(case_name, step, med_name)
        generated[case_dir / 'impact.export'] = export_text(case_name, med_name)
    return generated


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group()
    group.add_argument('--write', action='store_true', help='write generated text inputs (default)')
    group.add_argument('--check', action='store_true', help='fail if checked-in inputs differ')
    args = parser.parse_args()

    files = expected_files()
    if args.check:
        differences = []
        for path, expected in files.items():
            actual = path.read_text() if path.exists() else None
            if actual != expected:
                differences.append(str(path.relative_to(ROOT)))
        if differences:
            raise SystemExit('input generation mismatch: ' + ', '.join(differences))
        print(f'PASS: {len(files)} generated input files match')
        return

    for path, contents in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(contents)
    print(f'Wrote {len(files)} text inputs in {ROOT}')


if __name__ == '__main__':
    main()
