# Build-system adaptation only: upstream C/Fortran files remain byte-identical.
CC = gcc
FC = gfortran
CFLAGS = -Wall -O2 -I/usr/include/spooles -DARCH="Linux" -DSPOOLES -DARPACK -DMATRIXSTORAGE -DNETWORKOUT
FFLAGS = -Wall -O2 -fallow-argument-mismatch
include Makefile.inc
OBJECTS = $(SCCXF:.f=.o) $(SCCXC:.c=.o)
LIBS = -lspooles -larpack -llapack -lblas -lpthread -lm

ccx_2.21: ccx_2.21.o ccx_2.21.a
	$(FC) -O2 -o $@ ccx_2.21.o ccx_2.21.a $(LIBS) -fopenmp

ccx_2.21.a: $(OBJECTS)
	ar rcs $@ $(OBJECTS)

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.f
	$(FC) $(FFLAGS) -c $< -o $@
